### ISSUE TITLE
Tracing methods

### ISSUE THREAD

**Issue by AriMKatz** [zenbase-ai/core#22]
Can this trace through class methods? What about functions/methods with typed outputs?

**Comment by CyrusOfEden** [comment]
Re: classmethods @ammirsm 

Re: typed inputs/outputs yup! any python function

**Comment by CyrusOfEden** [comment]
Yeah exactly, this is our first step in the direction of a compiler. We'll have learned the experiences to do it right in Mojolang, Rust, etc. when the time comes

**Comment by ammirsm** [comment]
> Can this trace through class methods?

yes, I don't see any issue with that, but let us know if you saw any issues that you are ran into and we will fix it for you.
