### ISSUE TITLE
Some error with the few shot example

### ISSUE THREAD

**Issue by fredc1** [zenbase-ai/core#27]
py/cookbooks/labeled_few_shot/json.ipynb score is way lower than a naive llm with no optimization. Also the examples are clearly messed up in last cell:

Analyzing sample texts:
Text: I absolutely adore this new smartphone!
Sentiment: Positive
Reasoning: The text expresses a strong positive emotion towards the subject, indicating enthusiasm and satisfaction about the statement made.

Text: The customer service was terrible and unhelpful.
Sentiment: Positive
Reasoning: The text expresses a high level of satisfaction and enthusiasm, indicating a very positive sentiment towards the subject.

Text: The movie was okay, nothing special.
Sentiment: Positive
Reasoning: The text expresses a strong positive emotion toward something, indicating a high level of satisfaction and appreciation. The word 'great' reflects a positive sentiment.

**Comment by CyrusOfEden** [comment]
Hey @fredc1! Are you generating the reasoning before the sentiment? That can lead to confirmation bias. Can you try this with reasoning first then sentiment?

**Comment by fredc1** [comment]
I'm just commenting on the outputs already in your notebook committed to vc..... go look at the notebook on github I didn't run anything

[core](https://github.com/zenbase-ai/core/tree/main)/[py](https://github.com/zenbase-ai/core/tree/main/py)/[cookbooks](https://github.com/zenbase-ai/core/tree/main/py/cookbooks)/[labeled_few_shot](https://github.com/zenbase-ai/core/tree/main/py/cookbooks/labeled_few_shot)
/json.ipynb
